### PR TITLE
fix: Remove namespace dependency

### PR DESCRIPTION
**Pull request by adinhodovic**
To improve usage in non-k8s environments

### CODE REVIEW

**Comment by Ch00k** [comment]
I just discovered this project while trying to build some dashboards for my Django project running in Docker Compose. Is there anything preventing this PR from getting merged?

**Comment by adinhodovic** [comment]
Hey @Ch00k,

Yeah I opened this PR since I thought it was causing issues for docker setups, however it seems to be the time range and scrape interval that needed adjusting in all those issues.

What are you having for issues?

**Comment by Ch00k** [comment]
I am not sure what issues I _really_ had, but when I downloaded the dashboards from grafana.com, all of the panes displayed "No Data". I have since discovered #15 and this PR, and have imported the dashboards from that PR's branch. I do see data now. I will try to re-import the dashboards from grafana.com to see if that indeed was a time range issue.

For completeness sake, this is what my `prometheus.yml` looks:

```yml
scrape_configs:
  - job_name: 'mottle'
    static_configs:
      - targets: ['web:65432']
```

It does not define the `scrape_interval`, so the default `15s` is in use here.

**Comment by adinhodovic** [comment]
> I am not sure what issues I _really_ had, but when I downloaded the dashboards from grafana.com, all of the panes displayed "No Data". I have since discovered #15 and this PR, and have imported the dashboards from that PR's branch. I do see data now. I will try to re-import the dashboards from grafana.com to see if that indeed was a time range issue.
> 
> For completeness sake, this is what my `prometheus.yml` looks:
> 
> ```yaml
> scrape_configs:
>   - job_name: 'mottle'
>     static_configs:
>       - targets: ['web:65432']
> ```
> 
> It does not define the `scrape_interval`, so the default `15s` is in use here.

Cool, if it seems fixed I'll close this PR to not confuse people. It seems to work fine with docker setups. Did it work?

**Comment by Ch00k** [comment]
Could not get to it earlier, but I just re-imported the dashboards from `dashboards_out` in the `main` branch, and I do see data in the panels.

**Pull request closed without merging**
